# 벡터의 유사도 개념 파악하기

## 텍스트 임베딩
pip install openai  
pip install pandas

In [2]:
import openai
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd

In [ ]:
API_KEY = "API key"
client = openai.OpenAI(api_key = API_KEY)
embedding_result = client.embeddings.create(input = '저는 배가 고파요', model="text-embedding-ada-002")
print(embedding_result)

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.01663736067712307, -0.02178889885544777, 0.015218060463666916, -0.02722955122590065, -0.03682297468185425, 0.011774941347539425, -0.0345626063644886, -0.006715396419167519, -0.02399669960141182, -0.016821345314383507, -0.008134697563946247, 0.010822169482707977, -0.01055933628231287, -0.022669389843940735, 0.011308412067592144, -0.004934699274599552, 0.012070628814399242, -0.0029240227304399014, 0.008134697563946247, -0.016137978062033653, 0.00137576914858073, -0.014547835104167461, 0.018253788352012634, -0.012701429426670074, 0.0032525646965950727, 0.006432850379496813, 0.005342090968042612, -0.019016005098819733, -0.00918603129684925, -0.0017347012180835009, 0.034510038793087006, -0.016440236940979958, 0.00011386029655113816, 0.003149074036628008, 0.007372479885816574, -0.0054800789803266525, -0.006354000419378281, 0.0034726879093796015, -0.003784802509471774, -0.002250511897727847, -0.02243283949792385, -0.010362211614847183, 0.011354408226907253, -0.02473263442516327, 0.013292805291712284, 0.00908746849745512, -0.010572478175163269, -0.025560559704899788, -0.020133046433329582, 0.016427094116806984, 0.014232434332370758, -0.016151119023561478, -0.007832438684999943, -0.01743900403380394, 0.0008119091507978737, 0.026993002742528915, -0.009606565348803997, -0.0006731001776643097, 0.004438600968569517, -0.014127301052212715, 0.004701434634625912, 0.020330172032117844, -0.013811901211738586, 0.011860362254083157, -0.010289931669831276, 0.007865292951464653, 0.02227514050900936, 0.002822174923494458, -0.023786433041095734, 0.006311289966106415, 0.01801723800599575, 0.04176424443721771, -0.020593006163835526, -0.008739214390516281, 0.031881704926490784, -0.00680081732571125, -0.009803690016269684, 0.00031478420714847744, -0.0316714383661747, 0.01398274302482605, 0.031014354899525642, -0.022353990003466606, 0.001533469301648438, 0.00961313582956791, 0.00908746849745512, 0.011761799454689026, -0.032906755805015564, 0.015126069076359272, -0.03424720838665962, -0.005765910260379314, 0.005312522407621145, 0.024114975705742836, -0.010933874174952507, 0.036008190363645554, 0.005664062220603228, 0.008831205777823925, -0.012018062174320221, 0.03472030535340309, -0.008463239297270775, -0.018188079819083214, 0.0012689930154010653, -0.005220530554652214, -0.019541671499609947, -0.009310876950621605, -0.030725236982107162, -0.005039832554757595, 0.01973879709839821, 0.008233259432017803, 0.009494860656559467, -0.015112927183508873, 0.014468984678387642, 0.025744542479515076, 0.017964670434594154, -0.038767945021390915, -0.019633663818240166, 0.013148246333003044, -0.003765090135857463, -0.01590142771601677, -0.008325251750648022, -0.010565907694399357, -0.0021174524445086718, 0.014652968384325504, 0.0033215584699064493, 0.009383156895637512, 0.008489522151648998, 0.006160160526633263, -0.023089924827218056, -0.03277533873915672, 0.022564256563782692, 0.014705535024404526, 0.05301351845264435, 0.0180435199290514, 0.029516203328967094, -0.01212976686656475, -0.03464145585894585, -0.01772812008857727, -0.01590142771601677, -0.00042381903040222824, -0.020395880565047264, -0.02531086653470993, 0.008910056203603745, 0.023155633360147476, -0.011912928894162178, -0.03387923911213875, 0.021683765575289726, 0.02268253266811371, 0.0456278994679451, 0.005910468753427267, -0.008956052362918854, -9.543115447741002e-05, 0.00014804919192101806, -0.013062825426459312, 0.017425861209630966, -0.004027923569083214, 0.0014012311585247517, 0.011446399614214897, -0.014810668304562569, 0.020369596779346466, -0.0008714573923498392, -0.006101022940129042, 0.013194242492318153, 0.026638176292181015, 0.02038273960351944, -0.02783406898379326, 0.004277615342289209, 0.04152769595384598, -0.003666527569293976, -0.012169191613793373, -0.015980277210474014, -0.01590142771601677, 0.0039917840622365475, 0.01243202481418848, -0.011387261562049389, 0.016151119023561478, -0.023628732189536095, 0.014258718118071556, 0.019975347444415092, -0.00020667338685598224, -0.014574117958545685, 0.003942502662539482, -0.03311702236533165, -0.011032436974346638, 0.011268987320363522, 0.0071227881126105785, 0.011912928894162178, -0.008108413778245449, 0.010401636362075806, -0.01641395315527916, 0.01638766936957836, -0.007609030231833458, 0.013733050785958767, 0.03017328679561615, -0.005112112034112215, -0.011065291240811348, -0.619025468826294, -0.012714571319520473, 0.023510457947850227, -0.004593015648424625, 0.028464868664741516, 0.019239412620663643, -0.001053798128850758, 0.025836534798145294, 0.005381516180932522, 0.012136337347328663, -0.012274324893951416, 0.01944967918097973, 0.0012821347918361425, 0.0136016346514225, 0.01441641803830862, -0.012228329665958881, 0.032302238047122955, -0.005289524327963591, 0.012970834039151669, -0.013877609744668007, -0.032013121992349625, 0.007490755058825016, -0.015323193743824959, 0.0143507095053792, 0.030120721086859703, 0.01507350243628025, 0.011912928894162178, -0.006114164832979441, -0.019252555444836617, 0.053223785012960434, -0.01297740451991558, 0.036297306418418884, -0.009304306469857693, 0.002396713010966778, 0.041107162833213806, -0.017872678115963936, -0.009218885563313961, 0.027781503275036812, 0.021447215229272842, 0.037900593131780624, -0.012484591454267502, -0.020684996619820595, 0.004221763461828232, -0.0066398316994309425, 0.0013305946486070752, 0.00974455289542675, 0.019857071340084076, -0.008791781030595303, -0.001274742535315454, 0.001216426375322044, -0.01893715374171734, -0.0024180682376027107, -0.00530266622081399, 0.017557278275489807, -0.0037158087361603975, 0.011400403454899788, 0.010677611455321312, -0.02588910050690174, 6.375765951815993e-05, -0.002191374311223626, 0.014547835104167461, 0.003073509316891432, -0.0202513225376606, -0.0012123195920139551, -0.03190798684954643, 0.01779382862150669, -0.03432605788111687, 0.007129359059035778, -0.010388494469225407, -0.02675645239651203, -0.009409439750015736, -0.028044335544109344, -0.0071950675919651985, 0.015796294435858727, 0.03606075793504715, 0.002253797370940447, 0.0249954666942358, 0.0033314148895442486, -0.012727713212370872, -0.008726072497665882, 0.005765910260379314, 0.01411416009068489, -0.011262415908277035, -0.009961389936506748, 0.0005437368527054787, -0.00266776024363935, -0.030541254207491875, -0.009317448362708092, -0.0035712504759430885, -0.04152769595384598, 0.01888458803296089, 0.033327288925647736, 0.00458315946161747, -0.012655433267354965, -0.009008619002997875, -0.005325664300471544, 0.002746610203757882, -0.020790131762623787, 0.017097320407629013, -0.006334287580102682, -0.004865705501288176, -0.00454373424872756, 0.011341266334056854, -0.005046403501182795, 0.04620613157749176, -0.0013609847519546747, -0.03366897255182266, -0.022616824135184288, 0.0008316216408275068, -0.007812726311385632, 0.027544952929019928, 0.005884185433387756, 0.0007047223625704646, -0.003324843943119049, 0.036717843264341354, -0.021263230592012405, -1.3019755897403229e-05, -0.011216419748961926, 0.009652560576796532, -0.008036134764552116, 0.01612483523786068, -0.014258718118071556, 0.018608612939715385, -0.013161388225853443, -0.016151119023561478, 0.04102831333875656, -0.004326896741986275, -0.009941677562892437, -0.020882122218608856, 0.01070389524102211, -0.01926569640636444, -0.00918603129684925, 0.013890751637518406, -0.01686077006161213, 0.007648455444723368, -0.002505131997168064, 0.025967951864004135, -0.00028357270639389753, 0.021526064723730087, -0.025744542479515076, -0.02450922504067421, 0.013890751637518406, -0.03519340604543686, -0.0037913734558969736, 0.014285001903772354, -0.0034595460165292025, -0.0316714383661747, -0.016505945473909378, -0.0007342911558225751, 0.022353990003466606, 0.012050916440784931, 0.004044350702315569, -0.0015975349815562367, 0.009718269109725952, 0.01929198019206524, 0.0057199145667254925, 0.023024216294288635, -0.004799996968358755, -0.03046240471303463, 0.011636953800916672, 0.009396297857165337, -0.007779872044920921, -0.012044345960021019, -0.006679256446659565, 0.00977740716189146, -0.05059545114636421, -0.011393832974135876, 0.01390389259904623, -0.01919998787343502, -0.026730168610811234, -0.0038965067360550165, 0.004389319568872452, 0.01155153289437294, -0.025061175227165222, 0.00028275136719457805, 0.0012221758952364326, 0.020934689790010452, -0.008055847138166428, -0.018832020461559296, -0.02540285885334015, 0.0006332644843496382, 0.013430792838335037, -0.014061592519283295, 0.011124428361654282, 0.041264861822128296, 0.012583154253661633, 0.006597121246159077, 0.03298560529947281, -0.02722955122590065, 0.010381923988461494, -0.009435723535716534, 0.022485407069325447, -0.010427919216454029, 0.0005223816260695457, -0.010723607614636421, -0.01686077006161213, -0.011065291240811348, 0.03311702236533165, 0.0257576834410429, 0.0239047072827816, 0.008042705245316029, 0.00326734920963645, 0.015467752702534199, -0.008417243137955666, 0.016650503501296043, -0.037453774362802505, -0.007733876351267099, -0.01404845155775547, 0.011098145507276058, 0.011610670015215874, -0.007740446832031012, -0.023720724508166313, -0.006071454379707575, -0.0031523595098406076, 0.03017328679561615, 0.012050916440784931, -0.02031703107059002, 0.009882540442049503, -0.021802039816975594, 0.01442955993115902, -0.0016657074447721243, 0.013062825426459312, -0.001514578121714294, -0.01537576038390398, -0.010105948895215988, 0.005397943314164877, 0.0032985606230795383, 0.027781503275036812, 0.015572885982692242, -0.011676378548145294, -0.02584967575967312, 0.009008619002997875, -0.01855604536831379, 0.04179053008556366, 0.014994652010500431, -0.02546856738626957, 0.003965500742197037, -0.017005328088998795, 0.017110461369156837, 0.004957697354257107, -0.00529609527438879, 0.0030603676568716764, 0.005759339313954115, -0.009856256656348705, 0.009797119535505772, 0.02930593676865101, 0.0051055410876870155, 0.00509568490087986, -0.03992440924048424, 0.011236133053898811, -0.037742894142866135, -0.006301433313637972, -0.006140448153018951, -0.002028746297582984, -0.0002876794897019863, -0.03842626139521599, 0.00041252540540881455, 0.01111785788089037, 0.016650503501296043, 0.019239412620663643, 0.008200405165553093, 0.03472030535340309, -0.014324426651000977, 0.01683448627591133, 0.02386528253555298, -0.018924012780189514, -0.0016459948383271694, -0.02988417074084282, -0.03004186972975731, 0.0012804920552298427, -0.008068989031016827, -0.037033241242170334, 0.004221763461828232, -0.02294536493718624, 0.0016648860182613134, -0.01354906801134348, 0.01609855331480503, -0.017872678115963936, 0.021867748349905014, -0.02368129976093769, -0.003630387829616666, -0.04000326246023178, 0.008187264204025269, 0.019055429846048355, 0.009048043750226498, -0.029910454526543617, -0.02959505282342434, 0.006521556526422501, -0.03335357457399368, 0.0323285236954689, -0.008680076338350773, 0.013378226198256016, -0.010066523216664791, 0.01113757025450468, -0.046994633972644806, -0.02517945133149624, 0.02828088589012623, 0.004501023795455694, 0.010815599001944065, -0.024206966161727905, 0.0017034896882250905, -0.013292805291712284, -0.003640244249254465, -0.013995884917676449, 0.012215187773108482, 0.0032591356430202723, -0.0014119087718427181, -0.005079257767647505, 0.010270219296216965, -0.017202453687787056, -0.018582329154014587, -0.005752768367528915, -0.018832020461559296, -0.02000163123011589, -0.02009362168610096, -0.0090217599645257, -0.011328124441206455, -0.031408604234457016, 0.024233249947428703, 0.016887053847312927, -0.008390960283577442, 0.01537576038390398, -0.0119654955342412, -0.00167556363157928, 0.056141238659620285, -0.03280162066221237, 0.016808202490210533, -0.01347021758556366, 0.014915801584720612, 0.015086643397808075, -0.02524515986442566, -0.00765502592548728, 0.0036993816029280424, -0.0028944541700184345, 0.02297164872288704, -0.005187676288187504, 0.013522784225642681, 0.005611495580524206, 0.01343736331909895, 0.000756467692553997, -0.011899787001311779, -0.03663899004459381, 0.03356384113430977, -0.01964680477976799, -0.011242703534662724, -0.010579048655927181, 0.015218060463666916, 0.02397041581571102, 0.00820697657763958, 0.012471450492739677, 0.015047218650579453, -0.00029609838384203613, 0.0412122942507267, -0.014613543637096882, -0.007352767512202263, -0.00913346465677023, -0.009317448362708092, -0.009448864497244358, 0.007083363365381956, 0.033327288925647736, 0.005217245314270258, 0.0006381926359608769, -0.0008406565757468343, 0.02956877090036869, 0.015283768996596336, 0.021591773256659508, 0.014836952090263367, -0.005430797580629587, 0.0008123198058456182, -0.01565173640847206, 0.00029774109134450555, 0.011268987320363522, -0.010723607614636421, -0.013956459239125252, 0.04799339920282364, 0.009218885563313961, -0.026598751544952393, -0.004221763461828232, 0.021355222910642624, -0.0024410663172602654, 0.007287058979272842, 0.0180435199290514, 0.010881307534873486, 0.00095687824068591, 0.007661596871912479, -0.018411487340927124, 0.003224638756364584, -0.010769602842628956, -0.01849033683538437, -0.014534693211317062, -0.03542995825409889, -0.008436955511569977, -0.02243283949792385, -0.009724839590489864, -0.025113742798566818, -0.008594655431807041, -0.031119488179683685, -0.0419219471514225, -0.0060681686736643314, 0.010309644974768162, 0.032144539058208466, -0.023852141574025154, -0.018188079819083214, 0.00482299504801631, -0.005733055993914604, -0.023576166480779648, 0.012425454333424568, 0.0014603687450289726, -0.014022167772054672, 0.02680901810526848, 0.009343731217086315, -0.019305121153593063, 0.0006850098725408316, -0.008502664044499397, 0.023273907601833344, 0.013273091986775398, 0.012359745800495148, -0.004832851234823465, -0.0008410672307945788, 0.00045133443200029433, 0.003646814962849021, 0.010040240362286568, -0.007464471738785505, 0.013181100599467754, 0.02009362168610096, -0.028596285730600357, 0.0031999980565160513, -0.024075549095869064, 0.006097737699747086, 0.01353592611849308, 0.014363851398229599, 0.009284594096243382, -0.020750705152750015, 0.0161905437707901, 0.023116206750273705, -0.010165086016058922, 0.006787675432860851, -0.019686229526996613, 0.029069386422634125, 0.025113742798566818, -0.01846405491232872, 0.014836952090263367, -0.014298142865300179, 0.015336335636675358, -0.011170424520969391, -0.01973879709839821, 0.029095670208334923, 0.03180285543203354, -0.004280901048332453, 0.004885417874902487, -0.013181100599467754, -0.0242858175188303, -0.02326076664030552, -0.011426687240600586, 0.0012090341188013554, 0.015165493823587894, -0.022104298695921898, -0.014245576225221157, -0.007234492339193821, -0.007766730152070522, 0.000607391819357872, 5.7956844102591276e-05, 9.404511365573853e-05, -0.03269648924469948, -0.01596713624894619, 0.0034102648496627808, -0.00953428540378809, -0.009192601777613163, -0.009363443590700626, -0.024561792612075806, -0.014468984678387642, -0.008601226843893528, -0.0074973260052502155, 0.016781920567154884, 0.008016422390937805, 0.006873096339404583, 0.0032328523229807615, 0.00077700155088678, 0.005437368527054787, -0.02646733447909355, -0.004875561688095331, 0.013851325958967209, 0.053223785012960434, 0.01647966168820858, 0.026099367067217827, 0.018293213099241257, 0.0202513225376606, 0.01097329892218113, 0.0023802861105650663, -0.006984800565987825, -0.02169690653681755, 0.00776015967130661, -0.03206568956375122, 0.02655932679772377, -6.375765951815993e-05, 0.021420931443572044, 0.036560140550136566, 0.02783406898379326, 0.0018792595947161317, 0.03219710662961006, -0.006873096339404583, -0.004918272141367197, -0.025455426424741745, 0.012320321053266525, 0.006367141846567392, -0.025573700666427612, 0.010105948895215988, -0.0261125098913908, 0.011446399614214897, -0.018135512247681618, 0.007405334152281284, -0.020303888246417046, 0.01661107875406742, -0.017071036621928215, 0.03235480561852455, -0.05477450415492058, 0.004560161381959915, 0.025061175227165222, 0.011065291240811348, 0.002311292104423046, -0.018345778807997704, 0.011853791773319244, -0.013641059398651123, 0.0065346984192729, 0.025928525254130363, 0.0072410632856190205, -0.02217000722885132, 0.00011108822945971042, -0.004412317648530006, 0.019909638911485672, -0.026730168610811234, -0.018477195873856544, 0.010138803161680698, -0.01486323494464159, -0.018319495022296906, -0.015888286754488945, -0.028780270367860794, -0.04549648240208626, 0.01785953715443611, 0.002822174923494458, -0.016006560996174812, 0.023510457947850227, 0.007569605018943548, -0.01830635406076908, -0.01022422406822443, 0.030094437301158905, 0.003390552243217826, 0.011794653721153736, 0.04081804305315018, 0.02841230295598507, -0.0035679650027304888, -0.021894032135605812, 0.013141675852239132, 0.010027098469436169, -0.01411416009068489, -0.013851325958967209, 0.02691415138542652, -0.012570012360811234, -0.02038273960351944, 0.0008648865041323006, -0.0004324432520661503, 0.00458315946161747, 0.0012238185154274106, 0.0331433042883873, -0.0065642669796943665, 0.0013412722619250417, 0.010237365029752254, -0.0058874706737697124, -0.014955227263271809, 0.04147512838244438, -0.008226688951253891, -0.001476795761846006, -0.012188903987407684, -0.0367966927587986, -0.005762624554336071, -0.006675971206277609, -0.01009280700236559, 0.02828088589012623, 0.021999165415763855, -0.020579863339662552, -0.004274330101907253, -0.00017628325440455228, -0.0074841841123998165, 0.010165086016058922, -0.014285001903772354, 0.03267020732164383, -0.0057823373936116695, 0.003679669229313731, 0.005966320633888245, 0.00508911395445466, 0.003945787902921438, 0.00554250180721283, 0.0024410663172602654, 0.037296075373888016, -0.0048032826744019985, 0.009586852043867111, -0.0072410632856190205, 0.0390307754278183, 0.013627917505800724, 0.0017839825013652444, -0.0053322347812354565, -0.006554410792887211, -0.002324433997273445, -0.009836544282734394, -0.009882540442049503, -0.005729770753532648, -0.019988488405942917, -0.00677453400567174, -0.03726979345083237, 0.0004973302711732686, -0.026296492666006088, 0.011229561641812325, 0.012228329665958881, 0.04066034406423569, -0.011866932734847069, -0.019160563126206398, -0.013759334571659565, 0.02546856738626957, -0.014153584837913513, -0.023891566321253777, -0.0018135512946173549, 0.002925665583461523, -0.014547835104167461, 0.01398274302482605, -0.008988906629383564, 0.009718269109725952, -0.011978637427091599, 0.007523609325289726, 0.013174530118703842, -0.006873096339404583, 0.01933140493929386, -0.008180692791938782, -0.0002802872913889587, -0.016939619556069374, -0.011492395773530006, -0.00038624205626547337, 0.011242703534662724, -0.0005975355743430555, 0.01785953715443611, 0.007944143377244473, 0.013075967319309711, -0.019830789417028427, -0.010211082175374031, -0.0059827477671206, 0.014810668304562569, 0.026743309572339058, 0.028727702796459198, -0.025074318051338196, -0.03677040711045265, -0.0021798755042254925, -0.006311289966106415, -0.016295677050948143, -0.03650757670402527, -0.014009025879204273, 0.0005683774943463504, 0.020487872883677483, -0.002411497524008155, -0.02709813602268696, 0.021657481789588928, -0.017491569742560387, -0.028018051758408546, 0.005644349846988916, 0.009586852043867111, 0.004464884288609028, 0.002932236297056079, 0.03356384113430977, -0.0035548233427107334, 0.004274330101907253, -0.010375352576375008, 0.005289524327963591, -0.003224638756364584, -0.01692647859454155, -0.00040800796705298126, 0.006603692192584276, -0.027255835011601448, 0.03369525820016861, 0.006012316793203354, -0.024614358320832253, -0.019791362807154655, 0.008456667885184288, -0.02956877090036869, 0.0014685823116451502, 0.017320727929472923, 0.0154546108096838, 0.0050299763679504395, -0.005342090968042612, 0.0059038978070020676, 0.02633591741323471, -0.008358106017112732, 0.006551125552505255, -0.006886238232254982, -0.02172319032251835, -0.005795478820800781, -0.007641884498298168, -0.0038143713027238846, -0.028018051758408546, -0.022183148190379143, -0.01281970459

In [4]:
print(embedding_result.data[0].embedding)

[-0.01663736067712307, -0.02178889885544777, 0.015218060463666916, -0.02722955122590065, -0.03682297468185425, 0.011774941347539425, -0.0345626063644886, -0.006715396419167519, -0.02399669960141182, -0.016821345314383507, -0.008134697563946247, 0.010822169482707977, -0.01055933628231287, -0.022669389843940735, 0.011308412067592144, -0.004934699274599552, 0.012070628814399242, -0.0029240227304399014, 0.008134697563946247, -0.016137978062033653, 0.00137576914858073, -0.014547835104167461, 0.018253788352012634, -0.012701429426670074, 0.0032525646965950727, 0.006432850379496813, 0.005342090968042612, -0.019016005098819733, -0.00918603129684925, -0.0017347012180835009, 0.034510038793087006, -0.016440236940979958, 0.00011386029655113816, 0.003149074036628008, 0.007372479885816574, -0.0054800789803266525, -0.006354000419378281, 0.0034726879093796015, -0.003784802509471774, -0.002250511897727847, -0.02243283949792385, -0.010362211614847183, 0.011354408226907253, -0.02473263442516327, 0.013292805291712284, 0.00908746849745512, -0.010572478175163269, -0.025560559704899788, -0.020133046433329582, 0.016427094116806984, 0.014232434332370758, -0.016151119023561478, -0.007832438684999943, -0.01743900403380394, 0.0008119091507978737, 0.026993002742528915, -0.009606565348803997, -0.0006731001776643097, 0.004438600968569517, -0.014127301052212715, 0.004701434634625912, 0.020330172032117844, -0.013811901211738586, 0.011860362254083157, -0.010289931669831276, 0.007865292951464653, 0.02227514050900936, 0.002822174923494458, -0.023786433041095734, 0.006311289966106415, 0.01801723800599575, 0.04176424443721771, -0.020593006163835526, -0.008739214390516281, 0.031881704926490784, -0.00680081732571125, -0.009803690016269684, 0.00031478420714847744, -0.0316714383661747, 0.01398274302482605, 0.031014354899525642, -0.022353990003466606, 0.001533469301648438, 0.00961313582956791, 0.00908746849745512, 0.011761799454689026, -0.032906755805015564, 0.015126069076359272, -0.03424720838665962, -0.005765910260379314, 0.005312522407621145, 0.024114975705742836, -0.010933874174952507, 0.036008190363645554, 0.005664062220603228, 0.008831205777823925, -0.012018062174320221, 0.03472030535340309, -0.008463239297270775, -0.018188079819083214, 0.0012689930154010653, -0.005220530554652214, -0.019541671499609947, -0.009310876950621605, -0.030725236982107162, -0.005039832554757595, 0.01973879709839821, 0.008233259432017803, 0.009494860656559467, -0.015112927183508873, 0.014468984678387642, 0.025744542479515076, 0.017964670434594154, -0.038767945021390915, -0.019633663818240166, 0.013148246333003044, -0.003765090135857463, -0.01590142771601677, -0.008325251750648022, -0.010565907694399357, -0.0021174524445086718, 0.014652968384325504, 0.0033215584699064493, 0.009383156895637512, 0.008489522151648998, 0.006160160526633263, -0.023089924827218056, -0.03277533873915672, 0.022564256563782692, 0.014705535024404526, 0.05301351845264435, 0.0180435199290514, 0.029516203328967094, -0.01212976686656475, -0.03464145585894585, -0.01772812008857727, -0.01590142771601677, -0.00042381903040222824, -0.020395880565047264, -0.02531086653470993, 0.008910056203603745, 0.023155633360147476, -0.011912928894162178, -0.03387923911213875, 0.021683765575289726, 0.02268253266811371, 0.0456278994679451, 0.005910468753427267, -0.008956052362918854, -9.543115447741002e-05, 0.00014804919192101806, -0.013062825426459312, 0.017425861209630966, -0.004027923569083214, 0.0014012311585247517, 0.011446399614214897, -0.014810668304562569, 0.020369596779346466, -0.0008714573923498392, -0.006101022940129042, 0.013194242492318153, 0.026638176292181015, 0.02038273960351944, -0.02783406898379326, 0.004277615342289209, 0.04152769595384598, -0.003666527569293976, -0.012169191613793373, -0.015980277210474014, -0.01590142771601677, 0.0039917840622365475, 0.01243202481418848, -0.011387261562049389, 0.016151119023561478, -0.023628732189536095, 0.014258718118071556, 0.019975347444415092, -0.00020667338685598224, -0.014574117958545685, 0.003942502662539482, -0.03311702236533165, -0.011032436974346638, 0.011268987320363522, 0.0071227881126105785, 0.011912928894162178, -0.008108413778245449, 0.010401636362075806, -0.01641395315527916, 0.01638766936957836, -0.007609030231833458, 0.013733050785958767, 0.03017328679561615, -0.005112112034112215, -0.011065291240811348, -0.619025468826294, -0.012714571319520473, 0.023510457947850227, -0.004593015648424625, 0.028464868664741516, 0.019239412620663643, -0.001053798128850758, 0.025836534798145294, 0.005381516180932522, 0.012136337347328663, -0.012274324893951416, 0.01944967918097973, 0.0012821347918361425, 0.0136016346514225, 0.01441641803830862, -0.012228329665958881, 0.032302238047122955, -0.005289524327963591, 0.012970834039151669, -0.013877609744668007, -0.032013121992349625, 0.007490755058825016, -0.015323193743824959, 0.0143507095053792, 0.030120721086859703, 0.01507350243628025, 0.011912928894162178, -0.006114164832979441, -0.019252555444836617, 0.053223785012960434, -0.01297740451991558, 0.036297306418418884, -0.009304306469857693, 0.002396713010966778, 0.041107162833213806, -0.017872678115963936, -0.009218885563313961, 0.027781503275036812, 0.021447215229272842, 0.037900593131780624, -0.012484591454267502, -0.020684996619820595, 0.004221763461828232, -0.0066398316994309425, 0.0013305946486070752, 0.00974455289542675, 0.019857071340084076, -0.008791781030595303, -0.001274742535315454, 0.001216426375322044, -0.01893715374171734, -0.0024180682376027107, -0.00530266622081399, 0.017557278275489807, -0.0037158087361603975, 0.011400403454899788, 0.010677611455321312, -0.02588910050690174, 6.375765951815993e-05, -0.002191374311223626, 0.014547835104167461, 0.003073509316891432, -0.0202513225376606, -0.0012123195920139551, -0.03190798684954643, 0.01779382862150669, -0.03432605788111687, 0.007129359059035778, -0.010388494469225407, -0.02675645239651203, -0.009409439750015736, -0.028044335544109344, -0.0071950675919651985, 0.015796294435858727, 0.03606075793504715, 0.002253797370940447, 0.0249954666942358, 0.0033314148895442486, -0.012727713212370872, -0.008726072497665882, 0.005765910260379314, 0.01411416009068489, -0.011262415908277035, -0.009961389936506748, 0.0005437368527054787, -0.00266776024363935, -0.030541254207491875, -0.009317448362708092, -0.0035712504759430885, -0.04152769595384598, 0.01888458803296089, 0.033327288925647736, 0.00458315946161747, -0.012655433267354965, -0.009008619002997875, -0.005325664300471544, 0.002746610203757882, -0.020790131762623787, 0.017097320407629013, -0.006334287580102682, -0.004865705501288176, -0.00454373424872756, 0.011341266334056854, -0.005046403501182795, 0.04620613157749176, -0.0013609847519546747, -0.03366897255182266, -0.022616824135184288, 0.0008316216408275068, -0.007812726311385632, 0.027544952929019928, 0.005884185433387756, 0.0007047223625704646, -0.003324843943119049, 0.036717843264341354, -0.021263230592012405, -1.3019755897403229e-05, -0.011216419748961926, 0.009652560576796532, -0.008036134764552116, 0.01612483523786068, -0.014258718118071556, 0.018608612939715385, -0.013161388225853443, -0.016151119023561478, 0.04102831333875656, -0.004326896741986275, -0.009941677562892437, -0.020882122218608856, 0.01070389524102211, -0.01926569640636444, -0.00918603129684925, 0.013890751637518406, -0.01686077006161213, 0.007648455444723368, -0.002505131997168064, 0.025967951864004135, -0.00028357270639389753, 0.021526064723730087, -0.025744542479515076, -0.02450922504067421, 0.013890751637518406, -0.03519340604543686, -0.0037913734558969736, 0.014285001903772354, -0.0034595460165292025, -0.0316714383661747, -0.016505945473909378, -0.0007342911558225751, 0.022353990003466606, 0.012050916440784931, 0.004044350702315569, -0.0015975349815562367, 0.009718269109725952, 0.01929198019206524, 0.0057199145667254925, 0.023024216294288635, -0.004799996968358755, -0.03046240471303463, 0.011636953800916672, 0.009396297857165337, -0.007779872044920921, -0.012044345960021019, -0.006679256446659565, 0.00977740716189146, -0.05059545114636421, -0.011393832974135876, 0.01390389259904623, -0.01919998787343502, -0.026730168610811234, -0.0038965067360550165, 0.004389319568872452, 0.01155153289437294, -0.025061175227165222, 0.00028275136719457805, 0.0012221758952364326, 0.020934689790010452, -0.008055847138166428, -0.018832020461559296, -0.02540285885334015, 0.0006332644843496382, 0.013430792838335037, -0.014061592519283295, 0.011124428361654282, 0.041264861822128296, 0.012583154253661633, 0.006597121246159077, 0.03298560529947281, -0.02722955122590065, 0.010381923988461494, -0.009435723535716534, 0.022485407069325447, -0.010427919216454029, 0.0005223816260695457, -0.010723607614636421, -0.01686077006161213, -0.011065291240811348, 0.03311702236533165, 0.0257576834410429, 0.0239047072827816, 0.008042705245316029, 0.00326734920963645, 0.015467752702534199, -0.008417243137955666, 0.016650503501296043, -0.037453774362802505, -0.007733876351267099, -0.01404845155775547, 0.011098145507276058, 0.011610670015215874, -0.007740446832031012, -0.023720724508166313, -0.006071454379707575, -0.0031523595098406076, 0.03017328679561615, 0.012050916440784931, -0.02031703107059002, 0.009882540442049503, -0.021802039816975594, 0.01442955993115902, -0.0016657074447721243, 0.013062825426459312, -0.001514578121714294, -0.01537576038390398, -0.010105948895215988, 0.005397943314164877, 0.0032985606230795383, 0.027781503275036812, 0.015572885982692242, -0.011676378548145294, -0.02584967575967312, 0.009008619002997875, -0.01855604536831379, 0.04179053008556366, 0.014994652010500431, -0.02546856738626957, 0.003965500742197037, -0.017005328088998795, 0.017110461369156837, 0.004957697354257107, -0.00529609527438879, 0.0030603676568716764, 0.005759339313954115, -0.009856256656348705, 0.009797119535505772, 0.02930593676865101, 0.0051055410876870155, 0.00509568490087986, -0.03992440924048424, 0.011236133053898811, -0.037742894142866135, -0.006301433313637972, -0.006140448153018951, -0.002028746297582984, -0.0002876794897019863, -0.03842626139521599, 0.00041252540540881455, 0.01111785788089037, 0.016650503501296043, 0.019239412620663643, 0.008200405165553093, 0.03472030535340309, -0.014324426651000977, 0.01683448627591133, 0.02386528253555298, -0.018924012780189514, -0.0016459948383271694, -0.02988417074084282, -0.03004186972975731, 0.0012804920552298427, -0.008068989031016827, -0.037033241242170334, 0.004221763461828232, -0.02294536493718624, 0.0016648860182613134, -0.01354906801134348, 0.01609855331480503, -0.017872678115963936, 0.021867748349905014, -0.02368129976093769, -0.003630387829616666, -0.04000326246023178, 0.008187264204025269, 0.019055429846048355, 0.009048043750226498, -0.029910454526543617, -0.02959505282342434, 0.006521556526422501, -0.03335357457399368, 0.0323285236954689, -0.008680076338350773, 0.013378226198256016, -0.010066523216664791, 0.01113757025450468, -0.046994633972644806, -0.02517945133149624, 0.02828088589012623, 0.004501023795455694, 0.010815599001944065, -0.024206966161727905, 0.0017034896882250905, -0.013292805291712284, -0.003640244249254465, -0.013995884917676449, 0.012215187773108482, 0.0032591356430202723, -0.0014119087718427181, -0.005079257767647505, 0.010270219296216965, -0.017202453687787056, -0.018582329154014587, -0.005752768367528915, -0.018832020461559296, -0.02000163123011589, -0.02009362168610096, -0.0090217599645257, -0.011328124441206455, -0.031408604234457016, 0.024233249947428703, 0.016887053847312927, -0.008390960283577442, 0.01537576038390398, -0.0119654955342412, -0.00167556363157928, 0.056141238659620285, -0.03280162066221237, 0.016808202490210533, -0.01347021758556366, 0.014915801584720612, 0.015086643397808075, -0.02524515986442566, -0.00765502592548728, 0.0036993816029280424, -0.0028944541700184345, 0.02297164872288704, -0.005187676288187504, 0.013522784225642681, 0.005611495580524206, 0.01343736331909895, 0.000756467692553997, -0.011899787001311779, -0.03663899004459381, 0.03356384113430977, -0.01964680477976799, -0.011242703534662724, -0.010579048655927181, 0.015218060463666916, 0.02397041581571102, 0.00820697657763958, 0.012471450492739677, 0.015047218650579453, -0.00029609838384203613, 0.0412122942507267, -0.014613543637096882, -0.007352767512202263, -0.00913346465677023, -0.009317448362708092, -0.009448864497244358, 0.007083363365381956, 0.033327288925647736, 0.005217245314270258, 0.0006381926359608769, -0.0008406565757468343, 0.02956877090036869, 0.015283768996596336, 0.021591773256659508, 0.014836952090263367, -0.005430797580629587, 0.0008123198058456182, -0.01565173640847206, 0.00029774109134450555, 0.011268987320363522, -0.010723607614636421, -0.013956459239125252, 0.04799339920282364, 0.009218885563313961, -0.026598751544952393, -0.004221763461828232, 0.021355222910642624, -0.0024410663172602654, 0.007287058979272842, 0.0180435199290514, 0.010881307534873486, 0.00095687824068591, 0.007661596871912479, -0.018411487340927124, 0.003224638756364584, -0.010769602842628956, -0.01849033683538437, -0.014534693211317062, -0.03542995825409889, -0.008436955511569977, -0.02243283949792385, -0.009724839590489864, -0.025113742798566818, -0.008594655431807041, -0.031119488179683685, -0.0419219471514225, -0.0060681686736643314, 0.010309644974768162, 0.032144539058208466, -0.023852141574025154, -0.018188079819083214, 0.00482299504801631, -0.005733055993914604, -0.023576166480779648, 0.012425454333424568, 0.0014603687450289726, -0.014022167772054672, 0.02680901810526848, 0.009343731217086315, -0.019305121153593063, 0.0006850098725408316, -0.008502664044499397, 0.023273907601833344, 0.013273091986775398, 0.012359745800495148, -0.004832851234823465, -0.0008410672307945788, 0.00045133443200029433, 0.003646814962849021, 0.010040240362286568, -0.007464471738785505, 0.013181100599467754, 0.02009362168610096, -0.028596285730600357, 0.0031999980565160513, -0.024075549095869064, 0.006097737699747086, 0.01353592611849308, 0.014363851398229599, 0.009284594096243382, -0.020750705152750015, 0.0161905437707901, 0.023116206750273705, -0.010165086016058922, 0.006787675432860851, -0.019686229526996613, 0.029069386422634125, 0.025113742798566818, -0.01846405491232872, 0.014836952090263367, -0.014298142865300179, 0.015336335636675358, -0.011170424520969391, -0.01973879709839821, 0.029095670208334923, 0.03180285543203354, -0.004280901048332453, 0.004885417874902487, -0.013181100599467754, -0.0242858175188303, -0.02326076664030552, -0.011426687240600586, 0.0012090341188013554, 0.015165493823587894, -0.022104298695921898, -0.014245576225221157, -0.007234492339193821, -0.007766730152070522, 0.000607391819357872, 5.7956844102591276e-05, 9.404511365573853e-05, -0.03269648924469948, -0.01596713624894619, 0.0034102648496627808, -0.00953428540378809, -0.009192601777613163, -0.009363443590700626, -0.024561792612075806, -0.014468984678387642, -0.008601226843893528, -0.0074973260052502155, 0.016781920567154884, 0.008016422390937805, 0.006873096339404583, 0.0032328523229807615, 0.00077700155088678, 0.005437368527054787, -0.02646733447909355, -0.004875561688095331, 0.013851325958967209, 0.053223785012960434, 0.01647966168820858, 0.026099367067217827, 0.018293213099241257, 0.0202513225376606, 0.01097329892218113, 0.0023802861105650663, -0.006984800565987825, -0.02169690653681755, 0.00776015967130661, -0.03206568956375122, 0.02655932679772377, -6.375765951815993e-05, 0.021420931443572044, 0.036560140550136566, 0.02783406898379326, 0.0018792595947161317, 0.03219710662961006, -0.006873096339404583, -0.004918272141367197, -0.025455426424741745, 0.012320321053266525, 0.006367141846567392, -0.025573700666427612, 0.010105948895215988, -0.0261125098913908, 0.011446399614214897, -0.018135512247681618, 0.007405334152281284, -0.020303888246417046, 0.01661107875406742, -0.017071036621928215, 0.03235480561852455, -0.05477450415492058, 0.004560161381959915, 0.025061175227165222, 0.011065291240811348, 0.002311292104423046, -0.018345778807997704, 0.011853791773319244, -0.013641059398651123, 0.0065346984192729, 0.025928525254130363, 0.0072410632856190205, -0.02217000722885132, 0.00011108822945971042, -0.004412317648530006, 0.019909638911485672, -0.026730168610811234, -0.018477195873856544, 0.010138803161680698, -0.01486323494464159, -0.018319495022296906, -0.015888286754488945, -0.028780270367860794, -0.04549648240208626, 0.01785953715443611, 0.002822174923494458, -0.016006560996174812, 0.023510457947850227, 0.007569605018943548, -0.01830635406076908, -0.01022422406822443, 0.030094437301158905, 0.003390552243217826, 0.011794653721153736, 0.04081804305315018, 0.02841230295598507, -0.0035679650027304888, -0.021894032135605812, 0.013141675852239132, 0.010027098469436169, -0.01411416009068489, -0.013851325958967209, 0.02691415138542652, -0.012570012360811234, -0.02038273960351944, 0.0008648865041323006, -0.0004324432520661503, 0.00458315946161747, 0.0012238185154274106, 0.0331433042883873, -0.0065642669796943665, 0.0013412722619250417, 0.010237365029752254, -0.0058874706737697124, -0.014955227263271809, 0.04147512838244438, -0.008226688951253891, -0.001476795761846006, -0.012188903987407684, -0.0367966927587986, -0.005762624554336071, -0.006675971206277609, -0.01009280700236559, 0.02828088589012623, 0.021999165415763855, -0.020579863339662552, -0.004274330101907253, -0.00017628325440455228, -0.0074841841123998165, 0.010165086016058922, -0.014285001903772354, 0.03267020732164383, -0.0057823373936116695, 0.003679669229313731, 0.005966320633888245, 0.00508911395445466, 0.003945787902921438, 0.00554250180721283, 0.0024410663172602654, 0.037296075373888016, -0.0048032826744019985, 0.009586852043867111, -0.0072410632856190205, 0.0390307754278183, 0.013627917505800724, 0.0017839825013652444, -0.0053322347812354565, -0.006554410792887211, -0.002324433997273445, -0.009836544282734394, -0.009882540442049503, -0.005729770753532648, -0.019988488405942917, -0.00677453400567174, -0.03726979345083237, 0.0004973302711732686, -0.026296492666006088, 0.011229561641812325, 0.012228329665958881, 0.04066034406423569, -0.011866932734847069, -0.019160563126206398, -0.013759334571659565, 0.02546856738626957, -0.014153584837913513, -0.023891566321253777, -0.0018135512946173549, 0.002925665583461523, -0.014547835104167461, 0.01398274302482605, -0.008988906629383564, 0.009718269109725952, -0.011978637427091599, 0.007523609325289726, 0.013174530118703842, -0.006873096339404583, 0.01933140493929386, -0.008180692791938782, -0.0002802872913889587, -0.016939619556069374, -0.011492395773530006, -0.00038624205626547337, 0.011242703534662724, -0.0005975355743430555, 0.01785953715443611, 0.007944143377244473, 0.013075967319309711, -0.019830789417028427, -0.010211082175374031, -0.0059827477671206, 0.014810668304562569, 0.026743309572339058, 0.028727702796459198, -0.025074318051338196, -0.03677040711045265, -0.0021798755042254925, -0.006311289966106415, -0.016295677050948143, -0.03650757670402527, -0.014009025879204273, 0.0005683774943463504, 0.020487872883677483, -0.002411497524008155, -0.02709813602268696, 0.021657481789588928, -0.017491569742560387, -0.028018051758408546, 0.005644349846988916, 0.009586852043867111, 0.004464884288609028, 0.002932236297056079, 0.03356384113430977, -0.0035548233427107334, 0.004274330101907253, -0.010375352576375008, 0.005289524327963591, -0.003224638756364584, -0.01692647859454155, -0.00040800796705298126, 0.006603692192584276, -0.027255835011601448, 0.03369525820016861, 0.006012316793203354, -0.024614358320832253, -0.019791362807154655, 0.008456667885184288, -0.02956877090036869, 0.0014685823116451502, 0.017320727929472923, 0.0154546108096838, 0.0050299763679504395, -0.005342090968042612, 0.0059038978070020676, 0.02633591741323471, -0.008358106017112732, 0.006551125552505255, -0.006886238232254982, -0.02172319032251835, -0.005795478820800781, -0.007641884498298168, -0.0038143713027238846, -0.028018051758408546, -0.022183148190379143, -0.012819704599678516, 0.013194242492318153, -0.0019745368044823

In [5]:
len(embedding_result.data[0].embedding)

1536

In [6]:
data = ['저는 배가 고파요',
        '저기 배가 지나가네요',
        '굶어서 허기가 지네요',
        '허기 워기라는 게임이 있는데 즐거워',
        '스팀에서 재밌는 거 해야지',
        '스팀에어프라이어로 연어구이 해먹을거야']

df = pd.DataFrame(data, columns=['text'])
df

                   text
0             저는 배가 고파요
1           저기 배가 지나가네요
2           굶어서 허기가 지네요
3   허기 워기라는 게임이 있는데 즐거워
4        스팀에서 재밌는 거 해야지
5  스팀에어프라이어로 연어구이 해먹을거야

In [7]:
def embedding_func(text):
    client = openai.OpenAI(api_key = API_KEY)
    respons = client.embeddings.create(input = text, model="text-embedding-ada-002")
    embedding_result = respons.data[0].embedding
    return embedding_result

df['embedding'] = df.apply(lambda row: embedding_func(row.text), axis=1)
df

                   text                                          embedding
0             저는 배가 고파요  [-0.01663736067712307, -0.02178889885544777, 0...
1           저기 배가 지나가네요  [-0.003291434608399868, -0.02751476690173149, ...
2           굶어서 허기가 지네요  [-0.006181030999869108, -0.0069507937878370285...
3   허기 워기라는 게임이 있는데 즐거워  [-0.011329255998134613, -0.011715852655470371,...
4        스팀에서 재밌는 거 해야지  [-0.016108456999063492, -0.014401600696146488,...
5  스팀에어프라이어로 연어구이 해먹을거야  [-0.002138908952474594, -0.030034277588129044,...

## 코사인 유사도

In [8]:
def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

vec1 = np.array([0,1,1,1])
vec2 = np.array([1,0,1,1])
vec3 = np.array([2,0,2,2])

print('벡터1과 벡터2의 유사도 :',cos_sim(vec1, vec2))
print('벡터1과 벡터3의 유사도 :',cos_sim(vec1, vec3))
print('벡터2와 벡터3의 유사도 :',cos_sim(vec2, vec3))

벡터1과 벡터2의 유사도 : 0.6666666666666667
벡터1과 벡터3의 유사도 : 0.6666666666666667
벡터2와 벡터3의 유사도 : 1.0000000000000002

In [9]:
def return_answer_candidate(df, query):
    query_embedding = embedding_func(query)
    df["similarity"] = df.embedding.apply(lambda x: cos_sim(np.array(x),
                                                            np.array(query_embedding)))
    top_three_doc = df.sort_values("similarity",
                                ascending=False).head(3)
    return top_three_doc

In [10]:
sim_result = return_answer_candidate(df, '아무 것도 안 먹었더니 꼬르륵 소리가나네')
sim_result

,text,embedding,similarity
2,굶어서 허기가 지네요,"[-0.006181030999869108, -0.0069507937878370285...",0.838333
5,스팀에어프라이어로 연어구이 해먹을거야,"[-0.002138908952474594, -0.030034277588129044,...",0.821603
0,저는 배가 고파요,"[-0.01663736067712307, -0.02178889885544777, 0...",0.814259

# Langchain 사용하여 PDF 내용에 질문하기

# PDF 추출하기

pip install PyPDF2

In [11]:
# 패키지 불러오기
from PyPDF2 import PdfReader

In [12]:
# PDF 파일 경로를 지정하여 불러오기. 
pdf_reader = PdfReader('Summary of ChatGPTGPT-4 Research.pdf')

In [13]:
# 텍스트 추출하기
total_text = ""
for page in pdf_reader.pages:
    total_text += page.extract_text()

In [14]:
print(total_text)

Summary of ChatGPT/GPT-4 Research
and Perspective Towards the Future of Large
Language Models
Yiheng Liu1, Tianle Han∗1, Siyuan Ma1, Jiayue Zhang1,
Yuanyuan Yang1, Jiaming Tian1, Hao He1, Antong Li2, Mengshen
He1, Zhengliang Liu3, Zihao Wu3, Dajiang Zhu4, Xiang Li5, Ning
Qiang1, Dingang Shen6,7,8, Tianming Liu3, and Bao Ge†1
1School of Physics and Information Technology, Shaanxi Normal University, Xi'an
710119 China
2School of Life and Technology Biomedical-Engineering, Xi'an Jiaotong University,
Xi'an 710049, China
3School of Computing, The University of Georgia, Athens 30602, USA
4Department of Computer Science and Engineering, The University of Texas at
Arlington, Arlington 76019, USA
5Department of Radiology, Massachusetts General Hospital and Harvard Medical
School, Boston 02115, USA
6School of Biomedical Engineering, ShanghaiTech University, Shanghai 201210,
China
7Shanghai United Imaging Intelligence Co., Ltd., Shanghai 200230, China
8Shanghai Clinical Research and Trial Center, Shanghai 201210, China
Abstract
This paper presents a comprehensive survey of ChatGPT and GPT-4,
state-of-the-art large language models (LLM) from the GPT series, and
their prospective applications across diverse domains. Indeed, key innova-
tions such as large-scale pre-training that captures knowledge across the
entire world wide web, instruction ne-tuning and Reinforcement Learn-
ing from Human Feedback (RLHF) have played signicant roles in en-
hancing LLMs' adaptability and performance. We performed an in-depth
analysis of 194 relevant papers on arXiv, encompassing trend analysis,
word cloud representation, and distribution analysis across various appli-
cation domains. The ndings reveal a signicant and increasing interest
in ChatGPT/GPT-4 research, predominantly centered on direct natural
language processing applications, while also demonstrating considerable
potential in areas ranging from education and history to mathematics,
∗Co-rst author
†Corresponding author: bob ge@snnu.edu.cn
1arXiv:2304.01852v1  [cs.CL]  4 Apr 2023medicine, and physics. This study endeavors to furnish insights into Chat-
GPT's capabilities, potential implications, ethical concerns, and oer di-
rection for future advancements in this eld.
1 Introduction
Recent advances in natural language processing (NLP) have led to the devel-
opment of powerful language models such as the GPT (Generative Pre-trained
Transformer) series [1, 2, 3, 4, 5], including large language models (LLM) such
as ChatGPT and GPT-4. These models are pre-trained on vast amounts of
text data and have demonstrated exceptional performance in a wide range of
NLP tasks, including language translation, text summarization, and question-
answering. In particular, the ChatGPT model has demonstrated its potential
in various elds, including education, healthcare, reasoning, text generation,
human-machine interaction, and scientic research.
A key milestone of LLM development is InstructGPT [5], a framework that
allows for instruction ne-tuning of a pre-trained language model based on Re-
inforcement Learning from Human Feedback (RLHF) [6, 5]. This framework
enables an LLM to adapt to a wide range of NLP tasks, making it highly ver-
exible by leveraging human feedback. RLHF enables the model to
align with human preferences and human values, which signicantly improves
from large language models that are solely trained text corpora through unsu-
pervised pre-training. ChatGPT is a successor to InstructGPT. Since its release
in December 2022, ChatGPT has been equipped with these advanced develop-
ments, leading to impressive performances in various downstream NLP tasks
such as reasoning and generalized text generation. These unprecedented NLP
capabilities spur applications in diverse domains such as education, healthcare,
human-machine interaction, medicine and scientic research. ChatGPT has re-
ceived widespread attention and interest, leading to an increasing number of
applications and research that harness its exceeding potential. The open release
of the multi-modal GPT-4 model further expands the horizon of large language
models and empowers exciting developments that involve diverse data beyond
text.
The purpose of this paper is to provide a comprehensive survey of the existing
research on ChatGPT and its potential applications in various elds. To achieve
this goal, we conducted a thorough analysis of papers related to ChatGPT in
the arXiv repository. As of April 1st, 2023, there are a total of 194 papers
mentioning ChatGPT on arXiv. In this study, we conducted a trend analysis of
these papers and generated a word cloud to visualize the commonly used terms.
Additionally, we also examined the distribution of the papers across various
elds and presented the corresponding statistics. Figure 1 displays the daily
submission trend of papers related to ChatGPT, indicating a growing interest
in this eld. Figure 2 illustrates the word cloud analysis of all the papers. We
can observe that the current research is primarily focused on natural language
processing, but there is still signicant potential for research in other elds such
2Figure 1: The number of papers submitted by researchers per day.
3Figure 2: Word cloud analysis of all the 194 papers.
as education and history. This is further supported by Figure 3, which displays
the distribution of submitted papers across various elds, highlighting the need
for more research and development in these areas.
This paper aims to shed light on the promising capabilities of ChatGPT
and provide insight into its potential impact in the future, including ethical
considerations. Through this survey, we hope to provide insights into how these
models can be improved and extended in the future. In section 2, we will
review the existing work related to ChatGPT, including its applications, ethical
considerations, and evaluation. In addition to discussing the current state of
research related to ChatGPT, we will also explore its limitations in section 3.
Furthermore, we will provide guidance on future directions for language model
development.
2 Related work of ChatGPT
In this section, we review the latest research related to the application, ethics,
and evaluation of ChatGPT.
2.1 Application of ChatGPT
2.1.1 Question And Answering
In the education eld
ChatGPT is commonly used for question and answers testing in the edu-
cation sector. Users can use ChatGPT to learn, compare and verify answers
for dierent academic subjects such as physics, mathematics, and chemistry,
4Figure 3: The distribution of submitted papers across various elds.
5and/or conceptual subjects such as philosophy and religion. Additionally, users
can ask open-ended and analytical questions to understand the capabilities of
ChatGPT.
In the eld of mathematics, Frieder et al. [7] constructed the GHOSTS nat-
ural language dataset, which consists of graduate-level math test questions.
The authors tested ChatGPT's math abilities on the GHOSTS dataset us-
ing a question-and-answer format and evaluated it according to ne-grained
standards.In the Grad Text dataset, which covers simple set theory and logic
problems, ChatGPT performed the best. However, in the Olympiad-Problem-
Solving dataset, ChatGPT performed poorly, receiving only two 4-point scores
(out of a total of 5), with the majority of scores being 2 points. In the Holes-
in-Proofs dataset, ChatGPT received the lowest score of 1 point. In the MATH
dataset, ChatGPT only scored impressively in 26% of cases. These results sug-
gest that ChatGPT's math abilities are clearly lower than those of ordinary
math graduate students. Although ChatGPT can generally understand math
problems, it fails to provide the correct solutions. Pardos et al. [8] used the
Open Adaptive Tutoring system (OATutor) to investigate whether prompts gen-
erated by ChatGPT were helpful for learning algebra, with 77 participants from
Mechanical Turk taking part in the experiment. The experiment used ques-
tions from OpenStax's Elementary and Intermediate Algebra textbooks. These
participants were randomly assigned to either a control group (with manual
prompts) or an experimental group (with ChatGPT prompts). For each ques-
tion in both courses, the authors obtained answers from ChatGPT through a
question-and-answer format and evaluated scores according to three criteria:
ChatGPT provided an answer, the answer was correct, and inappropriate lan-
guage was not used in the answer. The study found that 70% of prompts gener-
ated by ChatGPT passed manual quality checks, and both humans and Chat-
GPT produced positive learning gains. However, the scores of human prompts
ranged from 74.59% to 84.32%, signicantly higher than those of ChatGPT
prompts. Shakarian et al. [9] studied the performance of ChatGPT on math
word problems (MWPs), using the DRAW-1K dataset for experimentation. The
dataset consists of 1000 MWPs and their answers, along with algebraic equa-
tion templates for solving such problems. The authors used the idea of machine
learning introspection and built performance prediction models using random
forests and XGBoost, and evaluated them on the dataset using ve-fold cross-
validation. ChatGPT's accuracy increased from an initial 34% to a nal 69%,
while its recall increased from an initial 41% to a nal 83%. The authors also
found that ChatGPT's failure rate decreased from an initial 84% to a nal
20%, indicating that performance can vary greatly depending on specic job
requirements.
In the eld of physics, Lehnert et al. [10] explored the capabilities and limita-
tions of ChatGPT by studying how it handles obscure physics topics such as the
swamp land conjecture in string theory. The experimental dialogue began with
broader and more general questions in the eld of string theory before narrowing
down to specic swamp land conjectures and examining ChatGPT's understand-
ing of them. The study found that ChatGPT could dene and explain dierent
6concepts in various styles, but was not eective in truly connecting various con-
cepts. It would condently provide false information and fabricate statements
when necessary, indicating that ChatGPT cannot truly create new knowledge
or establish new connections. However, in terms of identifying analogies and
describing abstract concepts of visual representation, ChatGPT can cleverly
use language. Kortemeyer et al. [11] evaluated ChatGPT's ability to answer
calculus-based physics questions through a question-and-answer test. The tests
included online homework, clicker questions, programming exercises, and exams
covering classical mechanics, thermodynamics, electricity and magnetism, and
modern physics. While ChatGPT was able to pass the course, it also demon-
strated many misconceptions and errors commonly held by beginners. West et
al. [12] used the Force Concept Inventory (FCI) to evaluate ChatGPT's accu-
racy in answering physics concept problems related to kinematics and Newtonian
mechanics in the rst semester of college physics. The FCI covers topics such
as kinematics, projectile motion, free fall, circular motion, and Newton's laws.
The study included data from 415 students who took the FCI at the end of the
semester, with an average score of 56%, while ChatGPT scored approximately
between 50% to 65%. The authors demonstrated that ChatGPT's performance
in physics learning can reach or even exceed the average level of a semester of
college physics.
In the medical eld
ChatGPT's question-answering capabilities can also be applied in the med-
ical eld, such as for answering medical questions from patients or assisting
healthcare professionals in diagnosing diseases. Nov et al. [13] evaluated the fea-
sibility of using ChatGPT for patient-doctor communication. The experiment
extracted 10 representative patient-doctor interactions from EHR, placed the
patient's questions in ChatGPT, and asked ChatGPT to respond using roughly
the same number of words as the doctor's response. Each patient's question was
answered by either the doctor or ChatGPT, and the patient was informed that
5 were answered by the doctor and 5 were generated by ChatGPT, and was
asked to correctly identify the source of the response. The results of the exper-
iment showed that the probability of correctly identifying ChatGPT's response
was 65.5%, while the probability of correctly identifying the doctor's response
was 65.1%. In addition, the experiment found that the patient's response to
the trustworthiness of ChatGPT's function was weakly positive (average Likert
score: 3.4), and trust decreased as the complexity of health-related tasks in
the questions increased. ChatGPT's responses to patient questions were only
slightly dierent from those of doctors, but people seem to trust ChatGPT to
answer low-risk health questions, while for complex medical questions, people
still tend to trust the doctor's responses and advice.
Tu et al. [14] explored the causal discovery ability of ChatGPT in the diag-
nosis of neuropathic pain. Causal relationship discovery aims to reveal potential
unknown causal relationships based purely on observed data [15]. The experi-
mental results found that ChatGPT has some limitations in understanding new
7knowledge and concepts beyond the existing textual training data corpus, that
is, it only understands language commonly used to describe situations and not
underlying knowledge. In addition, its performance consistency and stability are
not high, as the experiment observed that it would provide dierent answers for
the same question under multiple inquiries. However, despite the many limita-
tions of ChatGPT, we believe that it has a great opportunity to improve causal
relationship research.
In the other eld
Guo et al. [16] attempted to apply ChatGPT in the eld of communication,
specically using ChatGPT for ordered importance semantic communication,
where ChatGPT plays the role of an intelligent consulting assistant that can
replace humans in identifying the semantic importance of words in messages and
can be directly embedded into the current communication system. For a message
to be transmitted, the sender rst utilizes ChatGPT to output the semantic
importance order of each word. Then, the transmitter executes an unequal error
protection transmission strategy based on the importance order to make the
transmission of important words in the message more reliable. The experimental
results show that the error rate and semantic loss of important words measured
in the communication system embedded with ChatGPT are much lower than
those of existing communication schemes, indicating that ChatGPT can protect
important words well and make semantic communication more reliable.
Wang et al. [17] studied the eectiveness of ChatGPT in generating high-
quality Boolean queries for systematic literature search. They designed a wide
range of prompts and investigated these tasks on more than 100 systematic
review topics. In the end, queries generated by ChatGPT achieved higher accu-
racy compared to the currently most advanced query generation methods but
at the cost of reduced recall. For time-limited rapid reviews, it is often accept-
able to trade o higher precision for lower recall. Additionally, ChatGPT can
generate high search accuracy Boolean queries by guiding the prompts. How-
ever, it should be noted that when two queries use the same prompts, ChatGPT
generates dierent queries, indicating its limitations in consistency and stabil-
ity. Overall, this study demonstrated the potential of ChatGPT in generating
eective Boolean queries for systematic literature searches.
2.1.2 Text Classication
The purpose of text classication is to assign text data to predened categories.
This task is critical for many applications, including sentiment analysis, spam
detection, and topic modeling. While traditional machine learning algorithms
have been widely used for text classication, recent advances in natural lan-
guage processing have led to the development of more advanced techniques.
ChatGPT has shown immense potential in this eld. Its ability to accurately
exibility in handling various classication tasks, and potential for
customization make it a valuable tool for text classication, as evidenced by
several studies in the literature.
8Kuzman et al. [18] employed ChatGPT for automatic genre recognition, with
the goal of simplifying the text classication task by utilizing ChatGPT's zero-
shot classication capability. They compared ChatGPT's genre recognition per-
formance, using two prompt languages (EN and SL), with the X-GENRE clas-
sier based on the multilingual model XLM-RoBERTa on the English dataset
EN-GINCO and the Slovenian dataset GINCO. The results showed that when
EN was used as the prompt language, ChatGPT achieved Micro F1, Macro F1,
and Accuracy scores of 0.74, 0.66, and 0.72. However, on the GINCO dataset,
ChatGPT's genre recognition performance with both EN and SL prompt lan-
guages was lower than that of the X-GENRE classier to varying degrees.
Amin et al. [19] evaluated the text classication ability of ChatGPT in
aective computing by using it to perform personality prediction, sentiment
analysis, and suicide ideation detection tasks. They prompted ChatGPT with
corresponding prompts on three datasets: First Impressions, Sentiment140, and
Suicide and Depression, and compared its classication performance with three
baseline models: RoBERTa-base, Word2Vec, and BoW. The results showed
that ChatGPT's accuracy and UAR for the ve personality classications on
the First Impressions dataset were lower than the baseline methods to varying
degrees. On the Sentiment140 dataset, ChatGPT's accuracy and UAR were 85.5
and 85.5, respectively, which were better than the three baseline methods. On
the Suicide and Depression dataset, ChatGPT's accuracy and UAR were 92.7
and 91.2, respectively, which were lower than RoBERTa, the best-performing
baseline method.
Zhang et al. [20] employed ChatGPT for stance detection, which includes
support and opposition. They used ChatGPT to classify the political stance
of tweets in the SemEval-2016 and P-Stance datasets. SemEval-2016 contains
4,870 English tweets, and they selected tweets with the most commonly occur-
ring FM, LA, and HC political labels for stance classication. The P-Stance
dataset has 21,574 English tweets, and they classied the stance of tweets to-
wards Trump, Biden, and Bernie. The nal results showed that on the SemEval-
2016 dataset, ChatGPT achieved F1-m scores of 68.4, 58.2, and 79.5 for the FM,
LA, and HC political labels, and F1-avg scores of 72.6, 59.3, and 78.0, respec-
tively. On the P-Stance dataset, ChatGPT achieved F1-m scores of 82.8, 82.3,
and 79.4 for the Trump, Biden, and Bernie political gures, and F1-avg scores
of 83.2, 82.0, and 79.4, respectively.
Huang et al. [21] used ChatGPT to detect implicit hate speech in tweets.
They selected 12.5% (795 tweets) of the LatentHatred dataset containing im-
plicit hate speech and asked ChatGPT to classify them into three categories:
implicit hate speech, non-hate speech, and uncertain. The results showed that
ChatGPT correctly recognized 636 (80%) of the tweets. The number of tweets
classied as non-hate speech and uncertain were 146 (18.4%) and 13 (1.6%),
respectively. The results of the reclassication of tweets in the non-hate speech
and uncertain categories by Amazon Mechanical Turk (Mturk) workers were
consistent with ChatGPT's classication.
Overall, ChatGPT has tremendous potential in text classication tasks, as it
can eectively address problems such as genre identication, sentiment analysis,
9stance detection, and more. However, there are still challenges that ChatGPT
faces in the eld of text classication. Firstly, it struggles to perform well in
classication tasks with rare or out-of-vocabulary words since it heavily relies

# 텍스트 청크 사이즈로 자르기
pip install langchain

In [16]:
from langchain.text_splitter import CharacterTextSplitter

In [17]:
text_splitter = CharacterTextSplitter(
            separator="\n",
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len
        )

In [18]:
chunks = text_splitter.split_text(total_text)

In [19]:
len(chunks)

113

In [20]:
chunks[0]

"Summary of ChatGPT/GPT-4 Research\nand Perspective Towards the Future of Large\nLanguage Models\nYiheng Liu\x031, Tianle Han∗1, Siyuan Ma1, Jiayue Zhang1,\nYuanyuan Yang1, Jiaming Tian1, Hao He1, Antong Li2, Mengshen\nHe1, Zhengliang Liu3, Zihao Wu3, Dajiang Zhu4, Xiang Li5, Ning\nQiang1, Dingang Shen6,7,8, Tianming Liu3, and Bao Ge†1\n1School of Physics and Information Technology, Shaanxi Normal University, Xi'an\n710119 China\n2School of Life and Technology Biomedical-Engineering, Xi'an Jiaotong University,\nXi'an 710049, China\n3School of Computing, The University of Georgia, Athens 30602, USA\n4Department of Computer Science and Engineering, The University of Texas at\nArlington, Arlington 76019, USA\n5Department of Radiology, Massachusetts General Hospital and Harvard Medical\nSchool, Boston 02115, USA\n6School of Biomedical Engineering, ShanghaiTech University, Shanghai 201210,\nChina\n7Shanghai United Imaging Intelligence Co., Ltd., Shanghai 200230, China"

In [21]:
chunks[1]

"School, Boston 02115, USA\n6School of Biomedical Engineering, ShanghaiTech University, Shanghai 201210,\nChina\n7Shanghai United Imaging Intelligence Co., Ltd., Shanghai 200230, China\n8Shanghai Clinical Research and Trial Center, Shanghai 201210, China\nAbstract\nThis paper presents a comprehensive survey of ChatGPT and GPT-4,\nstate-of-the-art large language models (LLM) from the GPT series, and\ntheir prospective applications across diverse domains. Indeed, key innova-\ntions such as large-scale pre-training that captures knowledge across the\nentire world wide web, instruction \x0cne-tuning and Reinforcement Learn-\ning from Human Feedback (RLHF) have played signi\x0ccant roles in en-\nhancing LLMs' adaptability and performance. We performed an in-depth\nanalysis of 194 relevant papers on arXiv, encompassing trend analysis,\nword cloud representation, and distribution analysis across various appli-\ncation domains. The \x0cndings reveal a signi\x0ccant and increasing interest"

## 텍스트 임베딩 /시멘틱 인덱싱하기
pip install tiktoken  
pip install faiss-cpu

In [24]:
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings

In [ ]:
embeddings = OpenAIEmbeddings(openai_api_key="API key")

In [26]:
knowledge_base = FAISS.from_texts(chunks, embeddings)

## 사용자 질문 임베딩하여 시멘틱 Search 진행하기

In [38]:
docs = knowledge_base.similarity_search("where can i use chatGPT")
docs

[Document(id='7e34f2ae-27ec-4770-8e95-adfe1193d4f9', metadata={}, page_content='users to interact with systems, reducing the need for specialized knowledge or\ntraining. Some studies in the literature we collected have already demonstrated\nthis.\nTreude et al. [39] integrated ChatGPT into the prototype of "GPTCOM-\nCARE" to address programming query problems. This integration allowed for\nthe generation of multiple source code solutions for the same query, which in-\ncreased the e\x0eciency of software development. The results of their study demon-\nstrated the e\x0bectiveness of using ChatGPT to improve the quality and diversity\nof code solutions, ultimately reducing the amount of time and e\x0bort required for\nsoftware development.Wang et al. [83] proposed the chatCAD method, which\nutilizes large language models (LLMs) such as ChatGPT to enhance the out-\nput of multiple CAD networks for medical images, including diagnosis, lesion\nsegmentation, and report generation networks. The method generates sugges-'),
 Document(id='c55a7112-f198-4cb5-ab93-45c0e9843dcb', metadata={}, page_content="tasks. By analyzing the requirements for code generation, ChatGPT can pro-\nduce code snippets that accurately execute the intended functionality. This not\nonly saves time and e\x0bort in writing code from scratch but also reduces the risk\nof errors that may occur during manual coding. In addition, ChatGPT's ability\nto learn and adapt to new programming languages and frameworks enables it\nto complete more complex programming tasks. For example:\nMegahed et al. [38] discussed the potential of using ChatGPT for tasks\nsuch as code explanation, suggesting alternative methods for problem-solving\nwith code, and translating code between programming languages. The solutions\nprovided by ChatGPT were found to be viable. In another study, Treude et\nal. [39] introduced a ChatGPT-based prototype called GPTCOMCARE, which\nhelps programmers generate multiple solutions for a programming problem and\nhighlight the di\x0berences between each solution using colors.Sobania et al. [40]"),
 Document(id='366d5c95-fd26-467b-92f5-0f1293ed5602', metadata={}, page_content="The results showed that ChatGPT has great potential in generating complex\ntext output that is not easily captured by plagiarism detection software. The\nexisting plagiarism detection software should update their plagiarism detection\nengines. Basic et al. [36] conducted a comparison of the writing performance\nof students using or not using ChatGPT-3 as a writing aid. The experiment\nconsisted of two groups of 9 participants each. The control group wrote articles\nusing traditional methods, while the experimental group used ChatGPT as an\naid. Two teachers evaluated the papers. The study showed that the assistance of\nChatGPT did not necessarily improve the quality of the students' essays.Noever\net al. [37] discusses the potential of using arti\x0ccial intelligence (AI), particularly\nlanguage models like GPT (including GPT-3), to create more convincing chat-\nbots that can deceive humans into thinking they are interacting with another"),
 Document(id='53e5388f-76fb-4065-9c37-d9c26836ddf4', metadata={}, page_content='considerations. Through this survey, we hope to provide insights into how these\nmodels can be improved and extended in the future. In section 2, we will\nreview the existing work related to ChatGPT, including its applications, ethical\nconsiderations, and evaluation. In addition to discussing the current state of\nresearch related to ChatGPT, we will also explore its limitations in section 3.\nFurthermore, we will provide guidance on future directions for language model\ndevelopment.\n2 Related work of ChatGPT\nIn this section, we review the latest research related to the application, ethics,\nand evaluation of ChatGPT.\n2.1 Application of ChatGPT\n2.1.1 Question And Answering\nIn the education \x0celd\nChatGPT is commonly used for question and answers testing in the edu-\ncation sector. Users can use ChatGPT to learn, compare and verify answers\nfor di\x0berent academic subjects such as physics, mathematics, and chemistry,\n4Figure 3: The distribution of submitted papers across various \x0celds.')]

In [36]:
docs = knowledge_base.similarity_search_with_score("where can i use chatGPT")
docs

[(Document(id='7e34f2ae-27ec-4770-8e95-adfe1193d4f9', metadata={}, page_content='users to interact with systems, reducing the need for specialized knowledge or\ntraining. Some studies in the literature we collected have already demonstrated\nthis.\nTreude et al. [39] integrated ChatGPT into the prototype of "GPTCOM-\nCARE" to address programming query problems. This integration allowed for\nthe generation of multiple source code solutions for the same query, which in-\ncreased the e\x0eciency of software development. The results of their study demon-\nstrated the e\x0bectiveness of using ChatGPT to improve the quality and diversity\nof code solutions, ultimately reducing the amount of time and e\x0bort required for\nsoftware development.Wang et al. [83] proposed the chatCAD method, which\nutilizes large language models (LLMs) such as ChatGPT to enhance the out-\nput of multiple CAD networks for medical images, including diagnosis, lesion\nsegmentation, and report generation networks. The method generates sugges-'),
  np.float32(0.33266237)),
 (Document(id='c55a7112-f198-4cb5-ab93-45c0e9843dcb', metadata={}, page_content="tasks. By analyzing the requirements for code generation, ChatGPT can pro-\nduce code snippets that accurately execute the intended functionality. This not\nonly saves time and e\x0bort in writing code from scratch but also reduces the risk\nof errors that may occur during manual coding. In addition, ChatGPT's ability\nto learn and adapt to new programming languages and frameworks enables it\nto complete more complex programming tasks. For example:\nMegahed et al. [38] discussed the potential of using ChatGPT for tasks\nsuch as code explanation, suggesting alternative methods for problem-solving\nwith code, and translating code between programming languages. The solutions\nprovided by ChatGPT were found to be viable. In another study, Treude et\nal. [39] introduced a ChatGPT-based prototype called GPTCOMCARE, which\nhelps programmers generate multiple solutions for a programming problem and\nhighlight the di\x0berences between each solution using colors.Sobania et al. [40]"),
  np.float32(0.35264382)),
 (Document(id='366d5c95-fd26-467b-92f5-0f1293ed5602', metadata={}, page_content="The results showed that ChatGPT has great potential in generating complex\ntext output that is not easily captured by plagiarism detection software. The\nexisting plagiarism detection software should update their plagiarism detection\nengines. Basic et al. [36] conducted a comparison of the writing performance\nof students using or not using ChatGPT-3 as a writing aid. The experiment\nconsisted of two groups of 9 participants each. The control group wrote articles\nusing traditional methods, while the experimental group used ChatGPT as an\naid. Two teachers evaluated the papers. The study showed that the assistance of\nChatGPT did not necessarily improve the quality of the students' essays.Noever\net al. [37] discusses the potential of using arti\x0ccial intelligence (AI), particularly\nlanguage models like GPT (including GPT-3), to create more convincing chat-\nbots that can deceive humans into thinking they are interacting with another"),
  np.float32(0.3543974)),
 (Document(id='53e5388f-76fb-4065-9c37-d9c26836ddf4', metadata={}, page_content='considerations. Through this survey, we hope to provide insights into how these\nmodels can be improved and extended in the future. In section 2, we will\nreview the existing work related to ChatGPT, including its applications, ethical\nconsiderations, and evaluation. In addition to discussing the current state of\nresearch related to ChatGPT, we will also explore its limitations in section 3.\nFurthermore, we will provide guidance on future directions for language model\ndevelopment.\n2 Related work of ChatGPT\nIn this section, we review the latest research related to the application, ethics,\nand evaluation of ChatGPT.\n2.1 Application of ChatGPT\n2.1.1 Question And Answering\nIn the education \x0celd\nChatGPT is commonly used for question and answers testing in the edu-\ncation sector. Users can use ChatGPT to learn, compare and verify answers\nfor di\x0berent academic subjects such as physics, mathematics, and chemistry,\n4Figure 3: The distribution of submitted papers across various \x0celds.'),
  np.float32(0.35562247))]

## ChatGPT에게 최종 질문하기(load_qa_chain)

In [44]:
from langchain_community.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain

In [ ]:
llm = ChatOpenAI(temperature=0,
                    openai_api_key="api key",
                    max_tokens=3000,
                    model_name='gpt-3.5-turbo',
                    request_timeout=120
                    )

In [49]:
chain = load_qa_chain(llm, chain_type="stuff")

In [50]:
response = chain.run(input_documents=docs, question="where can i use chatGPT")
response

'You can use ChatGPT in various applications such as programming query problem-solving, generating code snippets, code explanation, suggesting alternative methods for problem-solving with code, translating code between programming languages, enhancing CAD networks for medical images, and in question and answering tasks in the education sector.'

In [51]:
print(response)

You can use ChatGPT in various applications such as programming query problem-solving, generating code snippets, code explanation, suggesting alternative methods for problem-solving with code, translating code between programming languages, enhancing CAD networks for medical images, and in question and answering tasks in the education sector.

## Langchain을 활용한 또다른 질문방법 RetrievalQA

pip install chromadb

In [52]:
from langchain.chains import RetrievalQA
from langchain.vectorstores import Chroma

In [54]:
db = Chroma.from_texts(chunks, embeddings)
retriever = db.as_retriever(search_type="similarity", search_kwargs={"k":2})

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\langchain\vectorstores\chroma.py", line 80, in __init__
    import chromadb
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\chromadb\__init__.py", line 4, in <module>
    import chromadb.config
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\chromadb\config.py", line 12, in <module>
    from pydantic import BaseSettings, validator
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\pydantic\__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\pydantic\_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.3/u/import-error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Zoon\AppData\Local\Temp\ipykernel_32792\4035084074.py", line 1, in <module>
    db = Chroma.from_texts(chunks, embeddings)
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\langchain\vectorstores\chroma.py", line 567, in from_texts
    chroma_collection = cls(
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\langchain\vectorstores\chroma.py", line 83, in __init__
    raise ImportError(
ImportError: Could not import chromadb python package. Please install it with `pip install chromadb`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\interactiveshell.py", line 2120, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\ultratb.py", line 1192, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\IPython\core\ultratb.py", line 792, in lines
    return self._sd.lines
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\stack_data\core.py", line 734, in lines
    pieces = self.included_pieces
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\stack_data\core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\stack_data\utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\stack_data\core.py", line 660, in executing_piece
    return only(
  File "c:\inflearn_chatgpt\ch10\ch10_env\lib\site-packages\executing\executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

In [57]:
qa = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=retriever, return_source_documents=True)
query = "where can i use chatGPT"
result = qa({"query": query})

In [59]:
print(result["result"])

ChatGPT can be used in various domains and applications. Some examples include:

1. Programming: ChatGPT can assist programmers by generating code snippets, suggesting alternative methods for problem-solving, and translating code between programming languages.

2. Software Development: ChatGPT can be integrated into software development tools to improve the efficiency and quality of code solutions, reducing the time and effort required for software development.

3. Medical Imaging: ChatGPT can enhance the output of CAD networks for medical images, including diagnosis, lesion segmentation, and report generation networks.

4. Natural Language Processing: ChatGPT can be used for tasks such as language translation, text summarization, and question-answering systems.

5. Customer Support: ChatGPT can be employed in customer support systems to provide automated responses and assist users with their queries.

These are just a few examples, and the potential applications of ChatGPT are vast. Its ability to understand and generate human-like text makes it useful in any scenario that requires natural language interaction and assistance.

In [61]:
print(result["source_documents"])

[Document(page_content='users to interact with systems, reducing the need for specialized knowledge or\ntraining. Some studies in the literature we collected have already demonstrated\nthis.\nTreude et al. [39] integrated ChatGPT into the prototype of "GPTCOM-\nCARE" to address programming query problems. This integration allowed for\nthe generation of multiple source code solutions for the same query, which in-\ncreased the e\x0eciency of software development. The results of their study demon-\nstrated the e\x0bectiveness of using ChatGPT to improve the quality and diversity\nof code solutions, ultimately reducing the amount of time and e\x0bort required for\nsoftware development.Wang et al. [83] proposed the chatCAD method, which\nutilizes large language models (LLMs) such as ChatGPT to enhance the out-\nput of multiple CAD networks for medical images, including diagnosis, lesion\nsegmentation, and report generation networks. The method generates sugges-', metadata={}), Document(page_content="tasks. By analyzing the requirements for code generation, ChatGPT can pro-\nduce code snippets that accurately execute the intended functionality. This not\nonly saves time and e\x0bort in writing code from scratch but also reduces the risk\nof errors that may occur during manual coding. In addition, ChatGPT's ability\nto learn and adapt to new programming languages and frameworks enables it\nto complete more complex programming tasks. For example:\nMegahed et al. [38] discussed the potential of using ChatGPT for tasks\nsuch as code explanation, suggesting alternative methods for problem-solving\nwith code, and translating code between programming languages. The solutions\nprovided by ChatGPT were found to be viable. In another study, Treude et\nal. [39] introduced a ChatGPT-based prototype called GPTCOMCARE, which\nhelps programmers generate multiple solutions for a programming problem and\nhighlight the di\x0berences between each solution using colors.Sobania et al. [40]", metadata={})]

## 이전 질문 기록을 포함하여 질분하는 방법 ConversationalRetrievalChain

We can now create a memory object, which is necessary to track the inputs/outputs and hold a conversation.

In [47]:
from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

We now initialize the ConversationalRetrievalChain

In [48]:
from langchain.chains import ConversationalRetrievalChain
qa = ConversationalRetrievalChain.from_llm(llm=llm, retriever=retriever, memory=memory)

NameError: name 'retriever' is not defined

In [49]:
chat_history = []
query = "where can i use chatGPT"
result = qa({"question": query, "chat_history": chat_history})
print(result["answer"])

NameError: name 'qa' is not defined

In [50]:
#이전 질문 및 답변 저장
chat_history = [(query, result["answer"])]
#다시 질문
query = "which field is the most used?"
result = qa({"question": query, "chat_history": chat_history})
print(result["answer"])

NameError: name 'result' is not defined